package com.example.codeledge.DatabaseOps;

import com.example.codeledge.ProgramData;

import java.util.ArrayList;
import java.util.List;

public class ProgramsInfo {
    public ProgramData[] GetProgramsData(){
        return  new ProgramData[] {
                new ProgramData("Merge Arrays", "Array", "<!-- HTML generated using hilite.me --><div style=\"background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;\"><pre style=\"margin: 0; line-height: 125%\"><span style=\"color: #008800; font-weight: bold\">public</span> <span style=\"color: #008800; font-weight: bold\">class</span> <span style=\"color: #BB0066; font-weight: bold\">ArrayMerge</span> <span style=\"color: #333333\">{</span>\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">private</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayA <span style=\"color: #333333\">=</span> <span style=\"color: #333333\">{</span><span style=\"color: #0000DD; font-weight: bold\">23</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">41</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">81</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">95</span><span style=\"color: #333333\">};</span>\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">private</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayB <span style=\"color: #333333\">=</span> <span style=\"color: #333333\">{</span><span style=\"color: #0000DD; font-weight: bold\">7</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">14</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">39</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">55</span><span style=\"color: #333333\">,</span> \n" +
                        "            <span style=\"color: #0000DD; font-weight: bold\">62</span><span style=\"color: #333333\">,</span> <span style=\"color: #0000DD; font-weight: bold\">74</span><span style=\"color: #333333\">};</span>\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">private</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayC <span style=\"color: #333333\">=</span> <span style=\"color: #008800; font-weight: bold\">new</span> <span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[</span>arrayA<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">length</span> \n" +
                        "            <span style=\"color: #333333\">+</span> arrayB<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">length</span><span style=\"color: #333333\">];</span>\n" +
                        "\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">public</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">void</span> <span style=\"color: #0066BB; font-weight: bold\">main</span><span style=\"color: #333333\">(</span>String<span style=\"color: #333333\">[]</span> args<span style=\"color: #333333\">)</span> <span style=\"color: #333333\">{</span>\n" +
                        "        merge<span style=\"color: #333333\">(</span>arrayA<span style=\"color: #333333\">,</span> arrayA<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">length</span><span style=\"color: #333333\">,</span> arrayB<span style=\"color: #333333\">,</span>\n" +
                        "                arrayB<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">length</span> <span style=\"color: #333333\">,</span> arrayC<span style=\"color: #333333\">);</span>\n" +
                        "        display<span style=\"color: #333333\">(</span>arrayC<span style=\"color: #333333\">,</span> arrayC<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">length</span><span style=\"color: #333333\">);</span>\n" +
                        "    <span style=\"color: #333333\">}</span>\n" +
                        "\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">private</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">void</span> <span style=\"color: #0066BB; font-weight: bold\">display</span><span style=\"color: #333333\">(</span><span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayC<span style=\"color: #333333\">,</span> \n" +
                        "                                <span style=\"color: #333399; font-weight: bold\">int</span> length<span style=\"color: #333333\">)</span> <span style=\"color: #333333\">{</span>\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">for</span> <span style=\"color: #333333\">(</span><span style=\"color: #333399; font-weight: bold\">int</span> i <span style=\"color: #333333\">=</span> <span style=\"color: #0000DD; font-weight: bold\">0</span><span style=\"color: #333333\">;</span> i <span style=\"color: #333333\">&lt;</span> length<span style=\"color: #333333\">;</span> i<span style=\"color: #333333\">++)</span> <span style=\"color: #333333\">{</span>\n" +
                        "            System<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">out</span><span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">println</span><span style=\"color: #333333\">(</span>arrayC<span style=\"color: #333333\">[</span>i<span style=\"color: #333333\">]</span> <span style=\"color: #333333\">+</span> <span style=\"background-color: #fff0f0\">&quot; &quot;</span><span style=\"color: #333333\">);</span>\n" +
                        "        <span style=\"color: #333333\">}</span>\n" +
                        "        System<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">out</span><span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">println</span><span style=\"color: #333333\">(</span><span style=\"background-color: #fff0f0\">&quot;&quot;</span><span style=\"color: #333333\">);</span>\n" +
                        "    <span style=\"color: #333333\">}</span>\n" +
                        "\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">public</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">void</span> <span style=\"color: #0066BB; font-weight: bold\">merge</span><span style=\"color: #333333\">(</span><span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayA<span style=\"color: #333333\">,</span> <span style=\"color: #333399; font-weight: bold\">int</span> sizeA<span style=\"color: #333333\">,</span> \n" +
                        "                             <span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayB<span style=\"color: #333333\">,</span> <span style=\"color: #333399; font-weight: bold\">int</span> sizeB<span style=\"color: #333333\">,</span> \n" +
                        "                             <span style=\"color: #333399; font-weight: bold\">int</span><span style=\"color: #333333\">[]</span> arrayC<span style=\"color: #333333\">){</span>\n" +
                        "        <span style=\"color: #333399; font-weight: bold\">int</span> aDex <span style=\"color: #333333\">=</span> <span style=\"color: #0000DD; font-weight: bold\">0</span><span style=\"color: #333333\">,</span> bDex<span style=\"color: #333333\">=</span><span style=\"color: #0000DD; font-weight: bold\">0</span><span style=\"color: #333333\">,</span> cDex<span style=\"color: #333333\">=</span><span style=\"color: #0000DD; font-weight: bold\">0</span><span style=\"color: #333333\">;</span>\n" +
                        "\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">while</span> <span style=\"color: #333333\">(</span>aDex <span style=\"color: #333333\">&lt;</span> sizeA <span style=\"color: #333333\">&amp;&amp;</span> bDex <span style=\"color: #333333\">&lt;</span> sizeB<span style=\"color: #333333\">){</span>\n" +
                        "            <span style=\"color: #008800; font-weight: bold\">if</span> <span style=\"color: #333333\">(</span>arrayA<span style=\"color: #333333\">[</span>aDex<span style=\"color: #333333\">]</span> <span style=\"color: #333333\">&lt;</span> arrayB<span style=\"color: #333333\">[</span>bDex<span style=\"color: #333333\">])</span> <span style=\"color: #333333\">{</span>\n" +
                        "                arrayC<span style=\"color: #333333\">[</span>cDex<span style=\"color: #333333\">++]</span> <span style=\"color: #333333\">=</span> arrayA<span style=\"color: #333333\">[</span>aDex<span style=\"color: #333333\">++];</span>\n" +
                        "            <span style=\"color: #333333\">}</span> <span style=\"color: #008800; font-weight: bold\">else</span> <span style=\"color: #333333\">{</span>\n" +
                        "                arrayC<span style=\"color: #333333\">[</span>cDex<span style=\"color: #333333\">++]</span> <span style=\"color: #333333\">=</span> arrayB<span style=\"color: #333333\">[</span>bDex<span style=\"color: #333333\">++];</span>\n" +
                        "            <span style=\"color: #333333\">}</span>\n" +
                        "        <span style=\"color: #333333\">}</span>\n" +
                        "\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">while</span> <span style=\"color: #333333\">(</span>aDex <span style=\"color: #333333\">&lt;</span> sizeA<span style=\"color: #333333\">){</span>\n" +
                        "            arrayC<span style=\"color: #333333\">[</span>cDex<span style=\"color: #333333\">++]</span> <span style=\"color: #333333\">=</span> arrayA<span style=\"color: #333333\">[</span>aDex<span style=\"color: #333333\">++];</span>\n" +
                        "        <span style=\"color: #333333\">}</span>\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">while</span> <span style=\"color: #333333\">(</span>aDex <span style=\"color: #333333\">&lt;</span> sizeB<span style=\"color: #333333\">){</span>\n" +
                        "            arrayC<span style=\"color: #333333\">[</span>cDex<span style=\"color: #333333\">++]</span> <span style=\"color: #333333\">=</span> arrayB<span style=\"color: #333333\">[</span>bDex<span style=\"color: #333333\">++];</span>\n" +
                        "        <span style=\"color: #333333\">}</span>\n" +
                        "    <span style=\"color: #333333\">}</span>\n" +
                        "<span style=\"color: #333333\">}</span>\n" +
                        "</pre></div>\n",  "0(n)"),

                new ProgramData("Buy n Sell Stock Twice", "Array", "<!-- HTML generated using hilite.me --><div style=\"background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;\"><pre style=\"margin: 0; line-height: 125%\"><span style=\"color: #008800; font-weight: bold\">import</span> <span style=\"color: #0e84b5; font-weight: bold\">java.util.ArrayList</span><span style=\"color: #333333\">;</span>\n" +
                        "<span style=\"color: #008800; font-weight: bold\">import</span> <span style=\"color: #0e84b5; font-weight: bold\">java.util.List</span><span style=\"color: #333333\">;</span>\n" +
                        "\n" +
                        "<span style=\"color: #008800; font-weight: bold\">public</span> <span style=\"color: #008800; font-weight: bold\">class</span> <span style=\"color: #BB0066; font-weight: bold\">BuyAndSellStockTwice</span> <span style=\"color: #333333\">{</span>\n" +
                        "    <span style=\"color: #008800; font-weight: bold\">public</span> <span style=\"color: #008800; font-weight: bold\">static</span> <span style=\"color: #333399; font-weight: bold\">double</span> <span style=\"color: #0066BB; font-weight: bold\">buyNSellStockTwice</span><span style=\"color: #333333\">(</span>List<span style=\"color: #333333\">&lt;</span>Double<span style=\"color: #333333\">&gt;</span> prices<span style=\"color: #333333\">){</span>\n" +
                        "        <span style=\"color: #333399; font-weight: bold\">double</span> maxTotalProfit <span style=\"color: #333333\">=</span> <span style=\"color: #6600EE; font-weight: bold\">0.0</span><span style=\"color: #333333\">;</span>\n" +
                        "        List<span style=\"color: #333333\">&lt;</span>Double<span style=\"color: #333333\">&gt;</span> firstBuySellProfits <span style=\"color: #333333\">=</span> <span style=\"color: #008800; font-weight: bold\">new</span> ArrayList<span style=\"color: #333333\">&lt;&gt;();</span>\n" +
                        "        <span style=\"color: #333399; font-weight: bold\">double</span> minPriceSoFar <span style=\"color: #333333\">=</span> Double<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">MAX_VALUE</span><span style=\"color: #333333\">;</span>\n" +
                        "\n" +
                        "        <span style=\"color: #888888\">// Forward phase. For each day record </span>\n" +
                        "        <span style=\"color: #888888\">// maximum profit, if we sell on that day</span>\n" +
                        "\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">for</span> <span style=\"color: #333333\">(</span><span style=\"color: #333399; font-weight: bold\">int</span> i <span style=\"color: #333333\">=</span> <span style=\"color: #0000DD; font-weight: bold\">0</span><span style=\"color: #333333\">;</span> i <span style=\"color: #333333\">&lt;</span> prices<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">size</span><span style=\"color: #333333\">();</span> i<span style=\"color: #333333\">++)</span> <span style=\"color: #333333\">{</span>\n" +
                        "            minPriceSoFar <span style=\"color: #333333\">=</span> Math<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">min</span><span style=\"color: #333333\">(</span>minPriceSoFar<span style=\"color: #333333\">,</span> \n" +
                        "                    prices<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">get</span><span style=\"color: #333333\">(</span>i<span style=\"color: #333333\">));</span>\n" +
                        "            maxTotalProfit <span style=\"color: #333333\">=</span> Math<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">max</span><span style=\"color: #333333\">(</span>maxTotalProfit<span style=\"color: #333333\">,</span> \n" +
                        "                    prices<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">get</span><span style=\"color: #333333\">(</span>i<span style=\"color: #333333\">)</span> <span style=\"color: #333333\">-</span> minPriceSoFar<span style=\"color: #333333\">);</span>\n" +
                        "            firstBuySellProfits<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">add</span><span style=\"color: #333333\">(</span>maxTotalProfit<span style=\"color: #333333\">);</span>\n" +
                        "        <span style=\"color: #333333\">}</span>\n" +
                        "\n" +
                        "        <span style=\"color: #888888\">//Backward phase. For each day, </span>\n" +
                        "        <span style=\"color: #888888\">// find the maximum profit if we make second buy</span>\n" +
                        "        <span style=\"color: #888888\">// on that day</span>\n" +
                        "\n" +
                        "        <span style=\"color: #333399; font-weight: bold\">double</span> maxPricesofar <span style=\"color: #333333\">=</span> Double<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">MIN_VALUE</span><span style=\"color: #333333\">;</span>\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">for</span> <span style=\"color: #333333\">(</span><span style=\"color: #333399; font-weight: bold\">int</span> i <span style=\"color: #333333\">=</span> prices<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">size</span><span style=\"color: #333333\">()</span> <span style=\"color: #333333\">-</span><span style=\"color: #0000DD; font-weight: bold\">1</span><span style=\"color: #333333\">;</span> i <span style=\"color: #333333\">&gt;</span> <span style=\"color: #0000DD; font-weight: bold\">0</span> <span style=\"color: #333333\">;</span> i<span style=\"color: #333333\">++)</span> <span style=\"color: #333333\">{</span>\n" +
                        "            maxPricesofar <span style=\"color: #333333\">=</span> Math<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">max</span><span style=\"color: #333333\">(</span>maxPricesofar<span style=\"color: #333333\">,</span> \n" +
                        "                    prices<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">get</span><span style=\"color: #333333\">(</span>i<span style=\"color: #333333\">));</span>\n" +
                        "            maxTotalProfit <span style=\"color: #333333\">=</span> Math<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">max</span><span style=\"color: #333333\">(</span>maxTotalProfit<span style=\"color: #333333\">,</span> \n" +
                        "                    maxPricesofar<span style=\"color: #333333\">-</span>prices<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">get</span><span style=\"color: #333333\">(</span>i<span style=\"color: #333333\">)</span> <span style=\"color: #333333\">+</span>\n" +
                        "                    firstBuySellProfits<span style=\"color: #333333\">.</span><span style=\"color: #0000CC\">get</span><span style=\"color: #333333\">(</span>i <span style=\"color: #333333\">-</span><span style=\"color: #0000DD; font-weight: bold\">1</span><span style=\"color: #333333\">));</span>\n" +
                        "        <span style=\"color: #333333\">}</span>\n" +
                        "        <span style=\"color: #008800; font-weight: bold\">return</span> maxTotalProfit<span style=\"color: #333333\">;</span>\n" +
                        "    <span style=\"color: #333333\">}</span>\n" +
                        "<span style=\"color: #333333\">}</span>\n" +
                        "</pre></div>\n", "0(n)")
        };
    }
}
